### ISSUE TITLE
启动时aiohttp模块报错

### ISSUE THREAD

**Issue by whale-song** [HibiKier/nonebot_plugin_gamedraw#14]
错误信息：
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_gamedraw/async_update_game_info.py", line 59, in async_update_game
    await asyncio.gather(*tasks)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_gamedraw/pretty_handle.py", line 87, in update_pretty_info
    data, code = await update_info(url, 'pretty')
  File "/home/ubuntu/.local/lib/python3.9/site-packages/nonebot_plugin_gamedraw/update_game_info.py", line 29, in update_info
    async with session.get(url, timeout=7) as response:
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/ubuntu/.local/lib/python3.9/site-packages/aiohttp/connector.py", line 971, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host wiki.biligame.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')]

运行时SSL验证出现问题

**Comment by HibiKier** [comment]
每次运行都是这样的报错吗看，一般是网络问题，可以尝试在update_game_info.py，
update_game_requests_info.py ，
update_game_simple_info.py  文件中的
```python
async with session.get(url, timeout=7) as response:
改为
async with session.get(url, timeout=7, verify_ssl=False) as response:
```

**Comment by whale-song** [comment]
> 每次运行都是这样的报错吗看，一般是网络问题，可以尝试在update_game_info.py，
> update_game_requests_info.py ，
> update_game_simple_info.py 文件中的
> 
> ```python
> async with session.get(url, timeout=7) as response:
> 改为
> async with session.get(url, timeout=7, verify_ssl=False) as response:
> ```

已经修改了，修改后不报错，感谢。
