### ISSUE TITLE
[Bug]: 方舟卡池下载/更新错误

### ISSUE THREAD

**Issue by KafCoppelia** [HibiKier/nonebot_plugin_gamedraw#25]
clone了最新repo，启动时下载方舟信息，debug模式下报错如下：
01-04 18:03:15 [INFO] nonebot_plugin_gamedraw | 蜜莓 is update...
01-04 18:03:15 [INFO] nonebot_plugin_gamedraw | 耶拉 is update...
01-04 18:03:16 [INFO] nonebot_plugin_gamedraw | 极光 is update...
01-04 18:03:16 [INFO] nonebot_plugin_gamedraw | 灵知 is update...
01-04 18:03:16 [ERROR] uvicorn | Traceback (most recent call last):
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/root/anaconda3/envs/nonebot_v2/lib/python3.9/site-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/root/NONEBOT/AQUABOT/src/plugins/nonebot_plugin_gamedraw/async_update_game_info.py", line 59, in async_update_game
    await asyncio.gather(*tasks)
  File "/root/NONEBOT/AQUABOT/src/plugins/nonebot_plugin_gamedraw/prts_handle.py", line 63, in update_prts_info
    data, code = await update_info(url, 'prts', ['头像', '名称', '阵营', '星级', '性别', '是否感染', '获取途径', '初始生命', '初始防御',
  File "/root/NONEBOT/AQUABOT/src/plugins/nonebot_plugin_gamedraw/update_game_info.py", line 54, in update_info
    member_dict = intermediate_check(member_dict, key, game_name, td)
  File "/root/NONEBOT/AQUABOT/src/plugins/nonebot_plugin_gamedraw/update_game_info.py", line 182, in intermediate_check
    msg = msg[:-1] if msg[-1] == '\n' else msg
IndexError: string index out of range

01-04 18:03:16 [ERROR] uvicorn | Application startup failed. Exiting.
🤔

**Comment by HibiKier** [comment]
已修
