### ISSUE TITLE
更新 請求被攔截

### ISSUE THREAD

**Issue by NAOLIU** [HibiKier/nonebot_plugin_gamedraw#65]
基本上每次請求都會顯示被攔截或者超時

07-22 04:36:53 [WARNING] nonebot_plugin_gamedraw | 访问 http://fgo.vgtime.com/equipment/ajax?wd=&ids=&sort=12958&o=desc&pn=19 超时, 重试 4/5
07-22 04:37:00 [ERROR] apscheduler | Job "dy_sched (trigger: interval[0:00:10], next run at: 2022-07-22 04:37:10 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\haruka_bot\plugins\pusher\dynamic_pusher.py", line 29, in dy_sched
    dynamics = (await get_user_dynamics(uid, proxies=PROXIES)).get("cards", [])
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\bilireq\dynamic\__init__.py", line 22, in get_user_dynamics
    return await get(url, params=params, auth=auth, reqtype=reqtype, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\bilireq\utils\__init__.py", line 82, in get
    return await request("GET", url, **kwargs)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\bilireq\utils\__init__.py", line 73, in request
    raise ResponseCodeError(
bilireq.exceptions.ResponseCodeError: 错误码: -412, 信息: 请求被拦截
07-22 04:37:01 [INFO] nonebot_plugin_gocqhttp | [2820096143] 收到群 罪猫的猫猫神教(129217699) 内 罪猫(1318185249) 的消息: 我真的急需铲屎官给我梳毛了 (-452734529)
07-22 04:37:01 [SUCCESS] nonebot | ONEBOT V11 2820096143 | [message.group.normal]: Message -452734529 from 1318185249@[群:129217699] "我真的急需铲屎官给我梳毛了"
07-22 04:37:01 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_anti_flash, type=message, priority=1, temp=False>
07-22 04:37:01 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_anti_flash, type=message, priority=1, temp=False> running complete
07-22 04:37:01 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False>
07-22 04:37:01 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_repeater, type=message, priority=10, temp=False> running complete
07-22 04:37:04 [WARNING] nonebot_plugin_gamedraw | 访问 http://fgo.vgtime.com/equipment/ajax?wd=&ids=&sort=12958&o=desc&pn=19 超时, 重试 5/5
07-22 04:37:05 [WARNING] nonebot_plugin_gamedraw | 更新 命运-冠位指定卡牌 page 19 出错
07-22 04:37:10 [ERROR] apscheduler | Job "dy_sched (trigger: interval[0:00:10], next run at: 2022-07-22 04:37:20 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nb_cli\handlers\deploy.py", line 24, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 258, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python3

**Comment by HibiKier** [comment]
降低异步请求数量，配置里有
