### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by Tamamoimoto** [HibiKier/nonebot_plugin_gamedraw#69]
启动后就报错了，请问是什么原因呢？

07-30 18:36:13 [ERROR] nonebot | Failed to import "nonebot_plugin_gamedraw"
Traceback (most recent call last):
  File "/mnt/disk01/nonebot2/bot/bot.py", line 25, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/dist-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_gamedraw/__init__.py", line 18, in <module>
    from .handles.azur_handle import AzurHandle
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_gamedraw/handles/azur_handle.py", line 3, in <module>
    from lxml import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory

**Comment by HibiKier** [comment]
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
