### ISSUE TITLE
方舟抽卡异常

### ISSUE THREAD

**Issue by ABKQPO** [HibiKier/nonebot_plugin_gamedraw#88]
04-20 21:07:55 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last):
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_gamedraw\__init__.py", line 72, in handler
    res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_gamedraw\handles\prts_handle.py", line 107, in draw
    index2card = self.get_cards(count)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_gamedraw\handles\prts_handle.py", line 82, in get_cards
    card = self.get_card(add)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_gamedraw\handles\prts_handle.py", line 73, in get_card
    acquire_operator = random.choice(all_operators)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by OnlyblackTea** [comment]
补充一下，同样是方舟抽卡异常，
指令为“方舟1井”
```
08-02 15:50:21 [WARNING] nonebot_plugin_gamedraw | Traceback (most recent call last):
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_gamedraw/__init__.py", line 72, in handler
    res = game.handle.draw(num, pool_name=pool_name, user_id=event.user_id)
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_gamedraw/handles/prts_handle.py", line 107, in draw
    index2card = self.get_cards(count)
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_gamedraw/handles/prts_handle.py", line 82, in get_cards
    card = self.get_card(add)
  File "/home/vbot/lib/python3.8/site-packages/nonebot_plugin_gamedraw/handles/prts_handle.py", line 73, in get_card
    acquire_operator = random.choice(all_operators)
  File "/home/vbot/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```
没有debug看细节，不知道其他人是否也能复现这个问题

**Comment by ABKQPO** [comment]
有人pr修复了，用pr的替换相应文件就行了
