### ISSUE TITLE
启动时出现如下报错

### ISSUE THREAD

**Issue by RandomEnch** [HibiKier/nonebot_plugin_gamedraw#9]
06-22 21:49:38 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\starlette\routing.py", line 526, in lifespan
    async for item in self.lifespan_context(app):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\starlette\routing.py", line 467, in default_lifespan
    await self.startup()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python39\site-packages\starlette\routing.py", line 502, in startup
    await handler()
  File "c:\program files\python39\lib\site-packages\nonebot_plugin_gamedraw\async_update_game_info.py", line 58, in async_update_game
    await asyncio.gather(*tasks)
  File "c:\program files\python39\lib\site-packages\nonebot_plugin_gamedraw\azur_handle.py", line 38, in update_azur_info
    data, code = await update_simple_info(url, 'azur')
  File "c:\program files\python39\lib\site-packages\nonebot_plugin_gamedraw\update_game_simple_info.py", line 36, in update_simple_info
    data = await retrieve_char_data(char, game_name, data, index)
  File "c:\program files\python39\lib\site-packages\nonebot_plugin_gamedraw\update_game_simple_info.py", line 128, in retrieve_char_data
    member_dict['头像'] = unquote(str(avatar_img['srcset']).split(' ')[-2])
TypeError: 'NoneType' object is not subscriptable

06-22 21:49:38 [ERROR] uvicorn | Application startup failed. Exiting.
请按任意键继续. . .

**Comment by HibiKier** [comment]
碧蓝wiki无头像错误，可能是新船？已修复

**Comment by RandomEnch** [comment]
那我这边该怎么修复呢？

**Comment by RandomEnch** [comment]
好的，谢谢
